// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.FriendFinder
{

    public class OnlineIdMatch
    {

        [JsonProperty("fromIndex")]
        public int FromIndex { get; set; }

        [JsonProperty("toIndex")]
        public int ToIndex { get; set; }
    }

}
