// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.Trophies
{

    public class Trophy
    {

        [JsonProperty("trophyId")]
        public int TrophyId { get; set; }

        [JsonProperty("trophyHidden")]
        public bool TrophyHidden { get; set; }

        [JsonProperty("trophyType")]
        public string TrophyType { get; set; }

        [JsonProperty("trophyName")]
        public string TrophyName { get; set; }

        [JsonProperty("trophyDetail")]
        public string TrophyDetail { get; set; }

        [JsonProperty("trophyIconUrl")]
        public string TrophyIconUrl { get; set; }

        [JsonProperty("trophyRare")]
        public int TrophyRare { get; set; }

        [JsonProperty("trophyEarnedRate")]
        public string TrophyEarnedRate { get; set; }

        [JsonProperty("comparedUser")]
        public ComparedUser ComparedUser { get; set; }

        [JsonProperty("fromUser")]
        public FromUser FromUser { get; set; }
    }

}
