// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.Authentication
{

    public class ParentalControl
    {

        [JsonProperty("RestrictChat")]
        public bool RestrictChat { get; set; }

        [JsonProperty("RestrictUGM")]
        public bool RestrictUGM { get; set; }

        [JsonProperty("RestrictStoreContent")]
        public bool RestrictStoreContent { get; set; }
    }

}
