// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;
using PlayStation_App.Models.MessageGroups;

namespace PlayStation_App.Models.Messages
{

    public class Message
    {

        [JsonProperty("messageUid")]
        public int MessageUid { get; set; }

        [JsonProperty("fakeMessageUid")]
        public object FakeMessageUid { get; set; }

        [JsonProperty("seenFlag")]
        public bool SeenFlag { get; set; }

        [JsonProperty("dataUsedFlag")]
        public bool DataUsedFlag { get; set; }

        [JsonProperty("messageKind")]
        public int MessageKind { get; set; }

        [JsonProperty("senderOnlineId")]
        public string SenderOnlineId { get; set; }

        [JsonProperty("sentMessageId")]
        public string SentMessageId { get; set; }

        [JsonProperty("receivedDate")]
        public string ReceivedDate { get; set; }

        [JsonProperty("contentKeys")]
        public string[] ContentKeys { get; set; }

        [JsonProperty("body")]
        public string Body { get; set; }

        [JsonProperty("voiceDataPlaybackTime")]
        public int? VoiceDataPlaybackTime { get; set; }

        [JsonProperty("stickerDetail")]
        public StickerDetail StickerDetail { get; set; }
    }

}
