// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.Events
{

    public class Duration
    {

        [JsonProperty("registerStartDate")]
        public string RegisterStartDate { get; set; }

        [JsonProperty("registerEndDate")]
        public string RegisterEndDate { get; set; }

        [JsonProperty("eventStartDate")]
        public string EventStartDate { get; set; }

        [JsonProperty("eventEndDate")]
        public string EventEndDate { get; set; }
    }

}
