// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.Trophies
{

    public class FromUser
    {

        [JsonProperty("onlineId")]
        public string OnlineId { get; set; }

        [JsonProperty("earned")]
        public bool Earned { get; set; }

        [JsonProperty("earnedDate")]
        public string EarnedDate { get; set; }
    }

}
