// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.MessageGroups
{

    public class LatestMessage
    {

        [JsonProperty("messageUid")]
        public float MessageUid { get; set; }

        [JsonProperty("seenFlag")]
        public bool SeenFlag { get; set; }

        [JsonProperty("messageKind")]
        public int MessageKind { get; set; }

        [JsonProperty("senderOnlineId")]
        public string SenderOnlineId { get; set; }

        [JsonProperty("receivedDate")]
        public string ReceivedDate { get; set; }

        [JsonProperty("body")]
        public string Body { get; set; }
    }

}
