// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.User
{

    public class AvatarUrl
    {

        [JsonProperty("size")]
        public string Size { get; set; }

        [JsonProperty("avatarUrl")]
        public string AvatarUrlLink { get; set; }
    }

}
