// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.User
{

    public class Presence
    {

        [JsonProperty("primaryInfo")]
        public PrimaryInfo PrimaryInfo { get; set; }
    }

}
