// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.User
{

    public class PrimaryInfo
    {

        [JsonProperty("onlineStatus")]
        public string OnlineStatus { get; set; }

        [JsonProperty("lastOnlineDate")]
        public string LastOnlineDate { get; set; }
    }

}
