// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.RecentActivity
{

    public class Feed
    {
        public bool IsPreviousButton { get; set; }

        public bool IsReloadButton { get; set; }
        public bool IsNextButton { get; set; }

        [JsonProperty("caption")]
        public string Caption { get; set; }

        [JsonProperty("targets")]
        public Target[] Targets { get; set; }

        [JsonProperty("captionTemplate")]
        public string CaptionTemplate { get; set; }

        [JsonProperty("captionComponents")]
        public CaptionComponent[] CaptionComponents { get; set; }

        [JsonProperty("storyId")]
        public string StoryId { get; set; }

        [JsonProperty("storyType")]
        public string StoryType { get; set; }

        [JsonProperty("source")]
        public Source Source { get; set; }

        [JsonProperty("smallImageUrl")]
        public string SmallImageUrl { get; set; }

        [JsonProperty("smallImageAspectRatio")]
        public string SmallImageAspectRatio { get; set; }

        [JsonProperty("largeImageUrl")]
        public string LargeImageUrl { get; set; }

        [JsonProperty("thumbnailImageUrl")]
        public string ThumbnailImageUrl { get; set; }

        [JsonProperty("date")]
        public string Date { get; set; }

        [JsonProperty("relevancy")]
        public double Relevancy { get; set; }

        [JsonProperty("commentCount")]
        public int CommentCount { get; set; }

        [JsonProperty("likeCount")]
        public int LikeCount { get; set; }

        [JsonProperty("titleId")]
        public string TitleId { get; set; }

        [JsonProperty("liked")]
        public bool Liked { get; set; }

        [JsonProperty("hasComments")]
        public bool HasComments { get; set; }

        [JsonProperty("reshareable")]
        public bool Reshareable { get; set; }

        [JsonProperty("condensedStories")]
        public CondensedStory[] CondensedStories { get; set; }

        [JsonProperty("productId")]
        public string ProductId { get; set; }

        [JsonProperty("productUrl")]
        public string ProductUrl { get; set; }

        [JsonProperty("serviceProviderName")]
        public string ServiceProviderName { get; set; }

        [JsonProperty("followStory")]
        public bool? FollowStory { get; set; }

        [JsonProperty("index")]
        public int? Index { get; set; }

        [JsonProperty("start")]
        public long? Start { get; set; }

        [JsonProperty("block")]
        public int? Block { get; set; }

        [JsonProperty("alwaysShow")]
        public bool? AlwaysShow { get; set; }

        [JsonProperty("storyComment")]
        public string StoryComment { get; set; }

        [JsonProperty("serviceProviderImageUrl")]
        public string ServiceProviderImageUrl { get; set; }

        [JsonProperty("params")]
        public Param[] Params { get; set; }
    }

}
