// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.Friends
{

    public class Friend
    {

        [JsonProperty("onlineId")]
        public string OnlineId { get; set; }

        [JsonProperty("region")]
        public string Region { get; set; }

        [JsonProperty("npId")]
        public string NpId { get; set; }

        [JsonProperty("avatarUrl")]
        public string AvatarUrl { get; set; }

        [JsonProperty("plus")]
        public int Plus { get; set; }

        [JsonProperty("trophySummary")]
        public TrophySummary TrophySummary { get; set; }

        [JsonProperty("relation")]
        public string Relation { get; set; }

        [JsonProperty("presence")]
        public Presence Presence { get; set; }
    }

}
