// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.TrophyDetail
{

    public class TrophyTitle
    {

        [JsonProperty("npCommunicationId")]
        public string NpCommunicationId { get; set; }

        [JsonProperty("trophyTitleName")]
        public string TrophyTitleName { get; set; }

        [JsonProperty("trophyTitleDetail")]
        public string TrophyTitleDetail { get; set; }

        [JsonProperty("trophyTitleIconUrl")]
        public string TrophyTitleIconUrl { get; set; }

        [JsonProperty("trophyTitlePlatfrom")]
        public string TrophyTitlePlatfrom { get; set; }

        [JsonProperty("hasTrophyGroups")]
        public bool HasTrophyGroups { get; set; }

        [JsonProperty("definedTrophies")]
        public DefinedTrophies DefinedTrophies { get; set; }

        [JsonProperty("comparedUser")]
        public ComparedUser ComparedUser { get; set; }

        [JsonProperty("fromUser")]
        public FromUser FromUser { get; set; }
    }

}
