// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.TrophyDetail
{

    public class ComparedUser
    {

        [JsonProperty("onlineId")]
        public string OnlineId { get; set; }

        [JsonProperty("progress")]
        public int Progress { get; set; }

        [JsonProperty("earnedTrophies")]
        public EarnedTrophies EarnedTrophies { get; set; }

        [JsonProperty("lastUpdateDate")]
        public string LastUpdateDate { get; set; }
    }

}
