// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.TrophyDetail
{

    public class EarnedTrophies
    {

        [JsonProperty("bronze")]
        public int Bronze { get; set; }

        [JsonProperty("silver")]
        public int Silver { get; set; }

        [JsonProperty("gold")]
        public int Gold { get; set; }

        [JsonProperty("platinum")]
        public int Platinum { get; set; }
    }

}
