// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.RecentActivity
{

    public class Target2
    {

        [JsonProperty("meta")]
        public string Meta { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

}
