// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.Friends
{

    public class GameTitleInfo
    {

        [JsonProperty("npTitleId")]
        public string NpTitleId { get; set; }

        [JsonProperty("titleName")]
        public string TitleName { get; set; }
    }

}
