// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.Friends
{

    public class PrimaryInfo
    {

        [JsonProperty("onlineStatus")]
        public string OnlineStatus { get; set; }

        [JsonProperty("lastOnlineDate")]
        public string LastOnlineDate { get; set; }

        [JsonProperty("platform")]
        public string Platform { get; set; }

        [JsonProperty("gameTitleInfo")]
        public GameTitleInfo GameTitleInfo { get; set; }

        [JsonProperty("gameStatus")]
        public string GameStatus { get; set; }
    }

}
