// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.Friends
{

    public class TrophySummary
    {

        [JsonProperty("level")]
        public int Level { get; set; }

        [JsonProperty("progress")]
        public int Progress { get; set; }

        [JsonProperty("earnedTrophies")]
        public EarnedTrophies EarnedTrophies { get; set; }

        public int TotalTrophies { get; set; }
    }

}
