// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.FriendFinder
{

    public class SearchResult
    {

        [JsonProperty("onlineId")]
        public string OnlineId { get; set; }

        [JsonProperty("onlineIdMatch")]
        public OnlineIdMatch OnlineIdMatch { get; set; }
    }

}
