// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.MessageGroups
{

    public class Member
    {

        [JsonProperty("onlineId")]
        public string OnlineId { get; set; }
    }

}
