// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.MessageGroups
{

    public class MessageGroupDetail
    {

        [JsonProperty("messageGroupType")]
        public int MessageGroupType { get; set; }

        [JsonProperty("totalMembers")]
        public int TotalMembers { get; set; }

        [JsonProperty("members")]
        public Member[] Members { get; set; }
    }

}
