// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PlayStation_App.Models.Events
{

    public class Event
    {

        [JsonProperty("eventId")]
        public string EventId { get; set; }

        [JsonProperty("eventType")]
        public string EventType { get; set; }

        [JsonProperty("eventName")]
        public string EventName { get; set; }

        [JsonProperty("lastUpdate")]
        public string LastUpdate { get; set; }

        [JsonProperty("duration")]
        public Duration Duration { get; set; }

        [JsonProperty("registeredUserCount")]
        public int RegisteredUserCount { get; set; }

        [JsonProperty("bannerImageUrl")]
        public string BannerImageUrl { get; set; }
    }

}
